'use client';

import React from 'react';
import {useEffect,useState} from 'react';

type World={id:number;name:string;code:string;status:string;currentGameDay:number;seasonLengthDays:number;daysRemaining:number;playerCount:number;freeCountries:number};
type Country={id:number;name:string;code:string;flag:string;status:string;isVipOnly:boolean;currentPlayer:any};
type Dash={country:any;world:any;last7Days:any[];recentTransactions:any[]};

const api=async(path:string,opts:RequestInit={})=>{const token=typeof window!=='undefined'?localStorage.getItem('jn_token'):null;const r=await fetch(path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(opts.headers||{})}});const j=await r.json();if(!r.ok)throw new Error(j.error||'خطا در ارتباط با سرور');return j};

export default function GameApp(){
 const [tab,setTab]=useState('home');const [worlds,setWorlds]=useState<World[]>([]);const [world,setWorld]=useState<World|null>(null);const [countries,setCountries]=useState<Country[]>([]);const [dash,setDash]=useState<Dash|null>(null);const [loading,setLoading]=useState(true);const [err,setErr]=useState('');const [search,setSearch]=useState('');const [tg,setTg]=useState<any>(null);
 useEffect(()=>{const w=window as any; if(w.Telegram?.WebApp){w.Telegram.WebApp.ready();w.Telegram.WebApp.expand();setTg(w.Telegram.WebApp); const init=w.Telegram.WebApp.initData; if(init) api('/api/auth/telegram',{method:'POST',body:JSON.stringify({initData:init})}).then(x=>{localStorage.setItem('jn_token',x.token);return loadWorlds()}).catch(e=>setErr(e.message)); else {setErr('بازی باید از داخل Telegram باز شود.');setLoading(false)}} else {setErr('Telegram WebApp در دسترس نیست.');setLoading(false)}},[]);
 async function loadWorlds(){try{setLoading(true);const ws=await api('/api/worlds');setWorlds(ws);const active=ws.find((x:World)=>x.status==='RUNNING'||x.status==='RECRUITING');if(active){setWorld(active);await loadCountries(active.id)}}catch(e:any){setErr(e.message)}finally{setLoading(false)}}
 async function loadCountries(id:number){try{setCountries(await api(`/api/worlds/${id}/countries`))}catch(e:any){setErr(e.message)}}
 async function choose(c:Country){if(!world)return;try{await api(`/api/worlds/${world.id}/countries/${c.id}/select`,{method:'POST',body:'{}'});await loadCountries(world.id);await loadDashboard(c.id);setTab('home')}catch(e:any){setErr(e.message)}}
 async function loadDashboard(id:number){try{setDash(await api(`/api/countries/${id}/dashboard`))}catch(e:any){setErr(e.message)}}
 useEffect(()=>{if(tab==='countries'&&world)loadCountries(world.id)},[tab,world?.id]);
 const visible=countries.filter(c=>c.name.includes(search));
 if(loading)return <main className="app"><div className="content"><div className="hero"><div className="brand">Empires</div><div className="sub">در حال اتصال به جهان بازی...</div></div></div></main>;
 return <main className="app"><header className="top"><div className="row"><div><div className="brand">Empires</div><div className="sub">Telegram Strategy Universe</div></div><span className="pill">{world?`روز ${world.currentGameDay}/${world.seasonLengthDays}`:'بدون جهان'}</span></div></header><div className="content">{err&&<div className="card error" style={{marginBottom:10}}>{err}</div>}
 {tab==='home'&&<Home dash={dash} world={world} onCountries={()=>setTab('countries')} />}
 {tab==='countries'&&<section><div className="hero"><div className="label">انتخاب کشور</div><h2 style={{margin:'5px 0'}}>کشور خودت را انتخاب کن</h2><div className="sub">انتخاب به‌صورت اتمیک انجام می‌شود.</div></div><div className="section"><input className="search" placeholder="جستجوی کشور..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="list">{visible.map(c=><div className="card" key={c.id}><div className="country"><span className="flag">{c.flag}</span><div style={{flex:1}}><b>{c.name}</b><div className="sub">{c.code} · {c.status==='FREE'?'آزاد':'تصاحب شده'}</div></div>{c.status==='FREE'&&<button className="btn" onClick={()=>choose(c)}>انتخاب</button>}</div></div>)}</div></div></section>}
 {tab==='economy'&&<Economy dash={dash}/>} {tab==='ranking'&&<Ranking world={world}/>} {tab==='more'&&<More tg={tg}/>} </div><nav className="nav">{[['home','خانه','⌂'],['countries','کشورها','🌍'],['economy','اقتصاد','▣'],['ranking','رتبه‌بندی','♜'],['more','بیشتر','⋯']].map(([k,t,i])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><div style={{fontSize:18}}>{i}</div>{t}</button>)}</nav></main>
}
function Home({dash,world,onCountries}:{dash:Dash|null;world:World|null;onCountries:()=>void}){if(!dash)return <><div className="hero"><div className="label">Empires</div><h1 style={{margin:'5px 0 8px'}}>کشورت را بساز.</h1><div className="sub">اقتصاد، زیرساخت، جمعیت و سیاست کشورت را در یک فصل ۳۰ روزه مدیریت کن.</div><button className="btn" style={{marginTop:15}} onClick={onCountries}>شروع بازی</button></div><div className="section grid"><div className="card"><div className="label">فصل</div><div className="value">۳۰ روز</div></div><div className="card"><div className="label">Game Day</div><div className="value">روز واقعی</div></div></div></>;
 const c=dash.country;return <><div className="hero"><div className="row"><div><div className="label">کشور من</div><h1 style={{margin:'4px 0'}}>{c.flag} {c.name}</h1><div className="sub">{c.governmentType} · رتبه {c.rank}</div></div><span className="pill">روز {dash.world.currentGameDay}</span></div></div><div className="section grid">{[['خزانه',Math.round(c.treasury).toLocaleString()+' ₮'],['جمعیت',Number(c.population).toLocaleString()],['رضایت',Math.round(c.satisfaction)+'٪'],['برق',`${Math.round(c.electricity.produced)}/${Math.round(c.electricity.consumed)}`],['زیرساخت',c.infrastructureLevel],['قدرت کشور',Math.round(c.armyPower)]].map(x=><div className="card" key={x[0]}><div className="label">{x[0]}</div><div className="value">{x[1]}</div></div>)}</div><div className="section card"><div className="row"><b>وضعیت فصل</b><span className="pill">{dash.world.daysRemaining} روز باقی</span></div><div className="metric"><span>درآمد ۷ روز</span><b>{Math.round(dash.last7Days.reduce((a,x)=>a+x.income,0)).toLocaleString()}</b></div><div className="metric"><span>هزینه ۷ روز</span><b>{Math.round(dash.last7Days.reduce((a,x)=>a+x.expense,0)).toLocaleString()}</b></div></div></>}
function Economy({dash}:{dash:Dash|null}){return <section><div className="hero"><div className="label">اقتصاد</div><h2 style={{margin:'5px 0'}}>دفتر مالی کشور</h2><div className="sub">هر تغییر مالی باید در Ledger ثبت شود.</div></div><div className="section list">{dash?.recentTransactions?.map((t:any)=><div className="card" key={t.id}><div className="row"><b>{t.type}</b><span className={t.amount>=0?'success':'error'}>{t.amount>=0?'+':''}{Math.round(t.amount).toLocaleString()}</span></div><div className="sub">روز {t.game_day} · {t.source||'SYSTEM'}</div></div>)||<div className="card">برای مشاهده دفتر مالی ابتدا کشور انتخاب کن.</div>}</div></section>}
function Ranking({world}:{world:World|null}){return <section><div className="hero"><div className="label">World Ranking</div><h2 style={{margin:'5px 0'}}>رتبه‌بندی جهان</h2><div className="sub">رتبه بر اساس وضعیت اقتصادی کشورها محاسبه می‌شود.</div></div><div className="section card"><div className="metric"><span>World</span><b>{world?.name||'—'}</b></div><div className="metric"><span>وضعیت</span><b>{world?.status||'—'}</b></div><div className="metric"><span>بازیکنان</span><b>{world?.playerCount||0}</b></div></div></section>}
function More({tg}:{tg:any}){return <section className="list"><div className="card"><b>Empires</b><p className="sub">Telegram Mini App · نسخه Vercel</p></div>{['بانک','بازار','نقشه جهان','دیپلماسی','پژوهش','ارتباطات','تنظیمات'].map(x=><div className="card" key={x}><div className="row"><b>{x}</b><span className="pill">در بازی</span></div></div>)}<div className="card"><button className="btn secondary" onClick={()=>tg?.requestFullscreen?.()}>تمام‌صفحه</button></div></section>}


function AdminCenter({ token }: { token: string }) {
  const [chats,setChats]=React.useState<any[]>([]);
  const [tgid,setTgid]=React.useState('');
  const [msg,setMsg]=React.useState('');
  const load=async()=>{const r=await fetch('/api/admin/required-chats',{headers:{Authorization:`Bearer ${token}`}}); if(r.ok)setChats(await r.json());};
  React.useEffect(()=>{load()},[]);
  const addChat=async()=>{setMsg(''); const title=prompt('نام کانال/گروه'); const chat_id=prompt('Chat ID یا @username'); if(!title||!chat_id)return; const r=await fetch('/api/admin/required-chats',{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({title,chat_id,username:chat_id,chat_type:'CHANNEL',is_required:true,is_active:true})}); setMsg(r.ok?'کانال اجباری اضافه شد':'خطا'); load();};
  const addUN=async()=>{if(!tgid)return; const r=await fetch('/api/admin/un-admins',{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({telegram_id:tgid})}); setMsg(r.ok?'UN Admin اضافه شد':'کاربر باید حداقل یک بار وارد بازی شده باشد');};
  return <section className="panel"><h2>⚙️ مدیریت Empires</h2><p>{msg}</p><button onClick={addChat}>+ افزودن کانال/گروه اجباری</button><ul>{chats.map(c=><li key={c.id}>{c.title} — {c.chat_id} {c.is_active?'🟢':'⚪'}</li>)}</ul><hr/><h3>🏛 سازمان ملل</h3><input value={tgid} onChange={e=>setTgid(e.target.value)} placeholder="Telegram ID" /><button onClick={addUN}>افزودن UN Admin</button></section>;
}
